package.json, yarn.lock
=> JDB-5481 - Remove docdash dependency

package.json, yarn.lock
=> JDB-5480 - Remove 'open' dependency

server/config/express.js
=> JDB-5491 - Redis session settings

charts/juror-public/values.stg.template.yaml
=> add stg template

config/development.json, config/production.json, config/test.json, server/components/auth/index.js, server/components/logger/juror-transport.js, server/components/pcqService/index.js, server/config/express.js, server/objects/ageSettings.js, server/objects/appSettings.js, server/routes/expense-calculator/confirm-information/confirm-information.controller.js, server/routes/steps/01-login/login.controller.js
The helm chart is currently using `juror` to mount the secret volumes. This is also used to know which keyvault to load from  `juror-$env`. So we need to change the code so it loads from `/mnt/secrets/juror` (which is where the helm chart mounts the secrets) - rather than `/mnt/secrets/juror-digital-vault`
```
[ ] Yes
[x] No
```
=> update vault name

charts/juror-public/Chart.yaml, charts/juror-public/values.dev.template.yaml, charts/juror-public/values.yaml
=> update api endpoint

server/config/express.js
=> JDB-5518 - Update CSP for GA4/Tag Manager

server/lib/appinsights.js
Alter logic for starting AppInsights
```
[ ] Yes
[x] No
```
=> alter appinsights trigger

server/lib/appinsights.js
=> Change the way app-insights gets triggered

config/development.json, config/production.json, config/test.json, server/lib/appinsights.js
Secrets retrieval doesn't allow secret to not be present, so set up defaults as empty and test for that instead
```
[ ] Yes
[x] No
```
=> alter insights

server/config/express.js
=> juror: add trust proxy setting

charts/juror-public/values.stg.template.yaml
=> add stg environment var

server/lib/utils.js
=> JDB-5542 - Refactor hearingDate format / DOB submit

config/development.json, config/production.json, config/test.json
=> JDB-5546 - FE Config files

client/js/i18n/cy/EXCUSAL_PAGE.json, client/js/i18n/en/EXCUSAL_PAGE.json
=> JDB-5458 - Update excusal guidance content

server/config/express.js
=> JDB-5559 - Public FE - SameSite session cookie attribute

server/routes/steps/07-confirm-information/confirm-information.controller.js
=> JDB-5531 - Check Answers hearing date/time deprecation warning

server/components/auth/index.js, server/objects/auth.js, server/objects/axios-instance.js, server/routes/steps/01-login/login.controller.js
=> JDB-5277 - Axios login/auth

server/objects/deferralHoliday.js, server/routes/steps/04-confirm-date/deferr/defer-check.controller.js
=> JDB-5277 - Axios / deferral holiday

server/objects/expenseCalculator.js, server/routes/expense-calculator/confirm-information/confirm-information.controller.js
=> JDB-5277 - Axios expenses calc

server/lib/utils.js
=> JDB-5564 - Refactor Utils RA submission

.dockerignore, Dockerfile, package.json, yarn.lock
=> update dockerignore & remove grunt-sonar-runner

server/components/pcqService/index.js, server/objects/appSettings.js, server/objects/axios-instance.js, server/objects/juror.js, server/routes/branches/03-third-party-personal-details/third-party-personal-details.controller.js, server/routes/steps/02-your-details/your-details.controller.js
=> JDB-5277 - Axios juror details / app-settings

server/components/pcqService/index.js, server/objects/pcqService.js
=> JDB-5277 - Axios PCQ service

server/config/express.js
=> JDB-5578 - Update express config / session name

client/js/i18n/cy/EXPENSE_CALCULATOR.json, client/js/i18n/en/EXPENSE_CALCULATOR.json
=> JDB-5585 - Expense calc FACT link url (EN)

server/objects/response.js, server/routes/steps/07-confirm-information/confirm-information.controller.js
=> JDB-5277 - Axios juror response post

infrastructure/state.tf
=> lock azure provider

server/objects/health.js, server/routes/actuator/actuator.controller.js, server/routes/actuator/index.js
=> JDB-5277 - Axios health actuator

server/routes/steps/03-qualify/qualify.controller.js, server/routes/steps/06-assistance/assistance.controller.js
=> JDB-5593 - Remove redis temp logging / update session save

client/js/i18n/cy/LOGIN_PAGE.json, client/js/i18n/en/LOGIN_PAGE.json, client/templates/includes/contact-details.njk, client/templates/steps/01-login/login.njk, client/templates/steps/01-login/summons-date.njk, server/routes/index.js, server/routes/steps/01-login/index.js, server/routes/steps/01-login/login.controller.js
=> JDB-5586 - Login summons date passed page

client/js/i18n/cy/EXPENSE_CALCULATOR.json, client/js/i18n/en/EXPENSE_CALCULATOR.json
=> JDB-5594 - Expense calc FACT link Welsh translation

server/routes/branches/02-third-party-reason/third-party-reason.controller.js, server/routes/branches/03-third-party-personal-details/index.js, server/routes/branches/03-third-party-personal-details/third-party-personal-details.controller.js
=> JDB-5573 - Refactor 3rd party juror details API calls

client/js/i18n/cy/COOKIE_SETTINGS_PAGE.json, client/js/i18n/en/COOKIE_SETTINGS_PAGE.json
=> JDB-5556-2 - Cookie policy Welsh content update

README.md
Blank line to force build
```
[ ] Yes
[ ] No
```
=> Blank line to force build

server/app.js, server/components/logger/index.js
https://centralgovernmentcgi.atlassian.net/browse/JM-7953
Stabilisation8 merge into Master
```
[ ] Yes
[ x] No
```
=> Stabilisation8 release

server/config/express.js
=> JM-8003 - Add CSRF error logging

server/config/express.js
=> JM-8003-1 - Update to CSRF error handler

server/config/validation/custom-validation.js
=> Stabilisation13

client/js/i18n/cy/VALIDATION.json
JM-8133
Fix third party date range validation error message
```
[ ] Yes
[x] No
```
=> JM-8133-2 Deferral date validation

server/app.js
JM-7990
Set defaults for age settings if null values are returned
```
[ ] Yes
[x] No
```
=> JM-7790 - Public default age settings

client/js/i18n/cy/LOGIN_PAGE.json, client/js/i18n/en/LOGIN_PAGE.json, client/templates/steps/01-login/locked.njk, server/routes/steps/01-login/index.js, server/routes/steps/01-login/login.controller.js
JM-8228
https://centralgovernmentcgi.atlassian.net/browse/JM-8228
Add authentication lock-out page
```
[ ] Yes
[x] No
```
=> JM-8228 - Public user authentication lock-out page

client/templates/contact.njk, server/config/express.js, server/routes/contact/contact.controller.js
[JS-120] https://tools.hmcts.net/jira/browse/JS-120
Update to webchat sccript ids on contact page
```
[ ] Yes
[x] No
```
=> JS-120 - Contact page Webchat script updates

package.json, server/app.js
JS-172
https://tools.hmcts.net/jira/secure/RapidBoard.jspa?rapidView=2832&projectKey=JS&view=detail&selectedIssue=JS-172&quickFilter=21157
App version number config for Juror front-end
```
[ ] Yes
[x] No
```
=> JS-172 - Public version number config

server/app.js
JS-172
https://tools.hmcts.net/jira/browse/JS-172
App version number config for Juror front-end
```
[ ] Yes
[x] No
```
=> JS-172a - Retrieve package settings

package.json, yarn.lock
JS-81
https://tools.hmcts.net/jira/browse/JS-81
Update cookie-parser dependency
```
[ ] Yes
[x] No
```
=> JS-81b - Update cookie-parser dependency

package.json
Update app version in package.json
```
[ ] Yes
[x] No
```
=> Update app version 5.2.0

package.json
JS-79
https://tools.hmcts.net/jira/browse/JS-79
Update package.json metadata
```
[ ] Yes
[x] No
```
=> JS-79 - Update package.json metadata

package.json
Juror Public Release 5.2
```
[ ] Yes
[x] No
```
=> Release5.2

client/js/i18n/cy/CHARACTER_COUNT.json, client/js/i18n/en/CHARACTER_COUNT.json, client/templates/branches/02-third-party-reason/index.njk, client/templates/steps/03-qualify/bail.njk, client/templates/steps/03-qualify/cjs-employed.njk, client/templates/steps/03-qualify/convictions.njk, client/templates/steps/03-qualify/mental-health-capacity.njk, client/templates/steps/03-qualify/mental-health-sectioned.njk, client/templates/steps/03-qualify/residency.njk, client/templates/steps/04-confirm-date/deferr.njk, client/templates/steps/04-confirm-date/excusal.njk, client/templates/steps/06-assistance/index.njk
[JS-101](https://tools.hmcts.net/jira/browse/JS-101)
Update character count text to include welsh translations.
```
[ ] Yes
[x] No
```
=> task/JS-101: Update character count translations

README.md, client/js/i18n/cy/CHARACTER_COUNT.json, client/js/i18n/en/CHARACTER_COUNT.json, client/templates/branches/02-third-party-reason/index.njk, client/templates/steps/03-qualify/bail.njk, client/templates/steps/03-qualify/cjs-employed.njk, client/templates/steps/03-qualify/convictions.njk, client/templates/steps/03-qualify/mental-health-capacity.njk, client/templates/steps/03-qualify/mental-health-sectioned.njk, client/templates/steps/03-qualify/residency.njk, client/templates/steps/04-confirm-date/deferr.njk, client/templates/steps/04-confirm-date/excusal.njk, client/templates/steps/06-assistance/index.njk, package.json
Juror Public Release 5.3
```
[ ] Yes
[x] No
```
=> Release5.3

charts/juror-public/Chart.yaml
=> helm: update to use oci

client/scss/custom-components/ds-datepicker.scss
https://tools.hmcts.net/jira/browse/JS-355
Update colours for DS Datepicker to GDS styles
```
[ ] Yes
[x] No
```
=> JS-355 - Map datepicker colours to GDS

client/templates/branches/03-third-party-personal-details/name-change.njk, client/templates/steps/01-login/login.njk, client/templates/steps/02-your-details/name-change.njk, server/config/validation/third-party-personal-details-name.js, server/config/validation/third-party-personal-details.js, server/config/validation/your-details-name.js, server/config/validation/your-details.js
https://tools.hmcts.net/jira/browse/JS-403
Branch for testing the Xerox file changes for last name (built on top of release5.8 branch)
```
[x ] Yes
[ ] No
```
=> task/JS-403: Update Last name to be 25 chars in Front End apps

package.json, yarn.lock
https://tools.hmcts.net/jira/browse/JS-457
Update GDS govuk-frontend
```
[ ] Yes
[x] No
```
=> JS-457 - Update GDS govuk-frontend

server/config/express.js
https://tools.hmcts.net/jira/browse/JS-544
Fix issue evaluating return URL for cookie page
```
[ ] Yes
[x] No
```
=> JS-544 - Fix incorrect return url on cookie page

server/routes/expense-calculator/confirm-information/confirm-information.controller.js
https://tools.hmcts.net/jira/browse/JS-556
Prevent incorrect code '400' error logging
```
[ ] Yes
[x] No
```
=> JS-556 - Public Expense Calculator '400' error logging
